Create pi.hi.md
microsoft/IoT-For-Beginners pull request #257
Opened 2021-07-24 10:32 UTC by AdityaGarg00

2021-07-26 17:32 UTC, Anurag-0-1-A requested changes
Great Work !!

Just some minor changes are required.

2021-07-26 17:32 UTC, Anurag-0-1-A commented on 1-getting-started/lessons/1-introduction-to-iot/translations/pi.hi.md
> +यदि आप सीधे अपने पीआई पर काम करना चाहते हैं, तो आप रास्पबेरी पाई ओएस के डेस्कटॉप संस्करण का उपयोग कर सकते हैं और अपने सभी आवश्यक टूल्स इंस्टॉल कर सकते हैं।
I think पीआई will be replaced by पाई

2021-07-26 17:32 UTC, Anurag-0-1-A commented on 1-getting-started/lessons/1-introduction-to-iot/translations/pi.hi.md
> +## हैलो वर्ल्डा
Replace हैलो वर्ल्डा with हैलो वर्ल्ड in the heading and in line 200 also

2021-07-27 17:15 UTC, Anurag-0-1-A requested changes
Nice Work !!

Just see some issues I've mentioned previously, Please.

2021-07-27 17:15 UTC, Anurag-0-1-A commented on 1-getting-started/lessons/1-introduction-to-iot/translations/pi.hi.md
> +यदि आप सीधे अपने पीआई पर काम करना चाहते हैं, तो आप रास्पबेरी पाई ओएस के डेस्कटॉप संस्करण का उपयोग कर सकते हैं और अपने सभी आवश्यक टूल्स इंस्टॉल कर सकते हैं।
Kindly check Line 30 again for resolving this error.

2021-07-27 17:15 UTC, Anurag-0-1-A commented on 1-getting-started/lessons/1-introduction-to-iot/translations/pi.hi.md
> +    पायथन की शक्तिशाली विशेषताओं में से एक [पिप पैकेज](https://pypi.org) स्थापित करने की क्षमता है - ये अन्य लोगों द्वारा लिखे गए कोड के पैकेज हैं और इंटरनेट पर प्रकाशित होते हैं। आप अपने कंप्यूटर पर
Please Check this again !!

2021-07-27 17:48 UTC, AdityaGarg00 commented
It's okay if that's repeated user will skip that portion it will just help him to explain better and I also discussed it with jim in the original pi.md file.

2021-07-27 17:53 UTC, Anurag-0-1-A approved these changes

2021-07-28 17:56 UTC, jimbobbennett approved these changes

2021-07-28 17:58 UTC, jimbobbennett commented
@AdityaGarg00 - can you update your branch from main please? There should be an option in GitHub to do this, but the button is missing for some reason. Once updated I'll merge this.

2021-07-29 16:03 UTC, jimbobbennett approved these changes

2021-07-29 16:06 UTC, merged