[PT] Portuguese Brazilian translation of 2 - farm
microsoft/IoT-For-Beginners pull request #405
Opened 2022-10-08 09:56 UTC by weslleymurdock

Suggest portuguese translation of following files:
* 1-getting-started/lessons/4-connect-internet/translations/README.pt.md
* 1-getting-started/lessons/4-connect-internet/translations/assignment.pt.md
* 1-getting-started/lessons/4-connect-internet/translations/wio-terminal-mqtt.pt.md
* 2-farm/lessons/1-predict-plant-growth/translations/README.pt.md
* 2-farm/lessons/1-predict-plant-growth/translations/assignment.pt.md
* 2-farm/lessons/1-predict-plant-growth/translations/pi-temp.pt.md
* 2-farm/lessons/1-predict-plant-growth/translations/single-board-computer-temp-publish.md
* 2-farm/lessons/1-predict-plant-growth/translations/virtual-device-temp.pt.md
* 2-farm/lessons/1-predict-plant-growth/translations/wio-terminal-temp-publish.pt.md
* 2-farm/lessons/1-predict-plant-growth/translations/wio-terminal-temp.pt.md
* 2-farm/lessons/4-migrate-your-plant-to-the-cloud/translations/wio-terminal-connect-hub.pt.md
* 2-farm/translations/README.pt.md
* translations/clean-up.pt.md

2022-10-08 10:25 UTC, weslleymurdock commented
> @microsoft-github-policy-service agree

2022-10-08 10:26 UTC, weslleymurdock commented
@microsoft-github-policy-service agree [company="{onboardcode}"]

2022-10-08 10:27 UTC, weslleymurdock commented
@microsoft-github-policy-service agree

2022-11-10 21:07 UTC, jimbobbennett commented
@annezao @elisabacelar - can you help with this? Would love a second person to review this before I merge as I'm not a Portuguese speaker.

2022-11-10 22:20 UTC, annezao commented
@jimbobbennett sure thing, i’ll check it out!

2022-11-11 19:04 UTC, annezao requested changes
Overall, the translation is correct. I have scored some broken link fixes and translation suggestions 🫡 🤘

2022-11-17 19:06 UTC, jimbobbennett commented
Thanks @annezao! Looking forward to the resolution on these comments so we can get this merged.

2022-12-05 16:52 UTC, jimbobbennett commented
@weslleymurdock - are you able to resolve the comments from @annezao?

2022-12-17 03:26 UTC, weslleymurdock commented
> @weslleymurdock - are you able to resolve the comments from @annezao?

Sorry by late response, this pasts weeks i've busy with my final tests
I'll try push this weekend

2023-03-16 02:46 UTC, annezao commented
Should I made the changes on @weslleymurdock branch, @jimbobbennett?

2023-03-16 15:04 UTC, jimbobbennett commented
> Should I made the changes on @weslleymurdock branch, @jimbobbennett?

Yes please!

2023-05-11 22:07 UTC, annezao commented
Oh no, I forget I don’t have access rights to the @weslleymurdock repo 😭

2023-05-11 22:24 UTC, annezao commented
I made the changes and only found this out later 🥲
@weslleymurdock could you give me access rights or accept this [PR](https://github.com/weslleymurdock/IoT-For-Beginners/pull/1)?

2025-08-23 22:27 UTC, leestott commented
Hi we are moving to using coop translator to translate this content to multiple languages see https://github.com/Azure/co-op-translator

2025-08-23 22:27 UTC, closed without merging

2025-08-23 22:27 UTC, leestott commented
Hi we are moving to using coop translator to translate this content to multiple languages see https://github.com/Azure/co-op-translator