Copy 1 files to .vi.md
microsoft/IoT-For-Beginners pull request #493
Opened 2024-05-29 08:58 UTC by JaxVN

**README.md** Update a link to **translations/README.vi.md**
Done
> 1. translations/README.vi.md - Done
> 2. translations/attributions.vi.md - Done
> 
Pending

> 4. translations/CODE_OF_CONDUCT.vi.md
> 5. translations/CONTRIBUTING.vi.md
> 6. translations/SECURITY.vi.md
> 7. translations/SUPPORT.vi.md
> 8. translations/TRANSLATIONS.vi.md
> 9. translations/clean-up.vi.md
> 10. translations/for-teachers.vi.md
> 11. translations/hardware.vi.md
> 12. translations/recommended-learning-model.vi.md

2024-05-29 08:59 UTC, JaxVN commented
@microsoft-github-policy-service agree

2025-08-20 22:19 UTC, WirelessLife approved these changes

2025-08-20 22:20 UTC, WirelessLife requested changes
Please remove any outside links

2025-08-29 13:28 UTC, leestott commented
translations are now automatic with Coop Translator

2025-08-29 13:28 UTC, closed without merging