Created pi.hi.md
microsoft/IoT-For-Beginners pull request #82
Opened 2021-06-15 06:11 UTC by AdityaGarg00

Translated pi.md file into local hindi

2021-07-21 13:32 UTC, Anurag-0-1-A requested changes

2021-07-22 08:34 UTC, AdityaGarg00 reviewed
I have done the required changes

2021-07-22 08:34 UTC, AdityaGarg00 commented on 1-getting-started/lessons/1-introduction-to-iot/translations/pi.hi.md
> +    * [सीधे अपने पाई पर काम करें](#सीधे-अपने-पाई-पर-काम-करें)
These are having the links to below sections of the file

2021-07-22 08:34 UTC, AdityaGarg00 commented on 1-getting-started/lessons/1-introduction-to-iot/translations/pi.hi.md
> +1. आवश्यक घटकों को स्थापित करने के लिए [एसएसएच दस्तावेज़ीकरण का उपयोग कर वीएस कोड रिमोट डेवलपमेंट](https://code.visualstudio.com/docs/remote/ssh?WT.mc_id=academic-17441-jabenn) में दिए गए निर्देशों क
Dastavejikaran is simpler word

2021-07-24 17:31 UTC, jimbobbennett commented
@AdityaGarg00 - I can't see the merge options, I think this is another issue from me making the repo public. Can you re-fork, copy your changes over and re-submit a new PR, then close this one please.

2021-07-28 08:01 UTC, closed without merging